apiVersion: v1
kind: Namespace
metadata:
  name: hpademo
---
apiVersion: v1
kind: Service
metadata:
 name: lb
 namespace: hpademo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: stresser-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hpademo
  labels:
    app: stresser-app
  name: stresser-app
spec:
  selector:
    matchLabels:
      app: stresser-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stresser-app
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: stresser
        ports:
         - containerPort: 80
        resources:
          requests:
            cpu: 0.2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: hpademo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stresser-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

        
    

